development:
  adapter: postgresql
  encoding: unicode
  database: test-blockchain-indexer
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: text-blockchain-indexer-test
  pool: 5
  username:
  password:
